/**
 * Curated emoji list for the picker overlay. Each entry has the glyph and a
 * comma-separated keyword string for fuzzy search. ~200 of the most-used
 * emojis grouped roughly by category. Not exhaustive — for the rare cases
 * users need a long-tail emoji, copy/paste from a browser still works.
 */

export interface EmojiEntry {
  char: string;
  keywords: string;
}

export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys & emotion
  { char: "😀", keywords: "grinning happy smile face" },
  { char: "😁", keywords: "beaming grin happy smile face" },
  { char: "😂", keywords: "joy laugh cry tears lol" },
  { char: "🤣", keywords: "rofl rolling laugh floor lmao" },
  { char: "😃", keywords: "smile happy face mouth open" },
  { char: "😄", keywords: "smile happy face eyes" },
  { char: "😅", keywords: "sweat smile happy nervous" },
  { char: "😆", keywords: "laugh xd squint" },
  { char: "😉", keywords: "wink flirt" },
  { char: "😊", keywords: "blush happy smile" },
  { char: "🙂", keywords: "slight smile mild" },
  { char: "🙃", keywords: "upside down sarcasm" },
  { char: "😇", keywords: "innocent halo angel" },
  { char: "😍", keywords: "heart eyes love crush" },
  { char: "🥰", keywords: "love hearts smiling" },
  { char: "😘", keywords: "kiss blow love" },
  { char: "😗", keywords: "kiss face" },
  { char: "😙", keywords: "kiss smile" },
  { char: "😚", keywords: "kiss closed eyes" },
  { char: "🥲", keywords: "smile tear happy cry" },
  { char: "😋", keywords: "yum tongue tasty" },
  { char: "😛", keywords: "tongue out playful" },
  { char: "😜", keywords: "tongue wink playful" },
  { char: "🤪", keywords: "zany crazy silly" },
  { char: "😝", keywords: "tongue squint silly" },
  { char: "🤑", keywords: "money mouth dollar" },
  { char: "🤗", keywords: "hug huggy hugs" },
  { char: "🤔", keywords: "thinking hmm pondering" },
  { char: "🤨", keywords: "raised eyebrow skeptical" },
  { char: "😐", keywords: "neutral meh blank" },
  { char: "😑", keywords: "expressionless deadpan" },
  { char: "😶", keywords: "no mouth speechless" },
  { char: "🙄", keywords: "eye roll annoyed" },
  { char: "😏", keywords: "smirk smug" },
  { char: "😣", keywords: "persevere strain" },
  { char: "😥", keywords: "sad relieved sweat" },
  { char: "😮", keywords: "wow surprise shock" },
  { char: "🤐", keywords: "zip mouth secret" },
  { char: "😯", keywords: "hushed surprised" },
  { char: "😪", keywords: "sleepy tired" },
  { char: "😫", keywords: "tired weary exhausted" },
  { char: "🥱", keywords: "yawn tired bored" },
  { char: "😴", keywords: "sleeping zzz tired" },
  { char: "😌", keywords: "relieved content peaceful" },
  { char: "😛", keywords: "tongue playful" },
  { char: "🥵", keywords: "hot heat sweat" },
  { char: "🥶", keywords: "cold freezing" },
  { char: "😱", keywords: "scream shock fear" },
  { char: "😨", keywords: "fearful scared" },
  { char: "😰", keywords: "anxious sweat scared" },
  { char: "😢", keywords: "cry sad tear" },
  { char: "😭", keywords: "sob cry loud sad" },
  { char: "😤", keywords: "huff angry triumph" },
  { char: "😡", keywords: "angry mad rage" },
  { char: "🤬", keywords: "swearing curse symbols" },
  { char: "😈", keywords: "devil smiling horns" },
  { char: "👿", keywords: "imp devil angry" },
  { char: "💀", keywords: "skull dead death" },
  { char: "💩", keywords: "poop crap" },
  { char: "🤡", keywords: "clown" },
  { char: "👻", keywords: "ghost spooky" },
  { char: "👽", keywords: "alien et" },
  { char: "🤖", keywords: "robot bot ai" },
  { char: "🎃", keywords: "pumpkin halloween" },

  // Hands & gestures
  { char: "👍", keywords: "thumbs up like ok yes" },
  { char: "👎", keywords: "thumbs down dislike no" },
  { char: "👌", keywords: "ok hand perfect" },
  { char: "🤌", keywords: "pinched fingers italian" },
  { char: "🤏", keywords: "pinching small bit" },
  { char: "✌️", keywords: "victory peace v" },
  { char: "🤞", keywords: "crossed fingers hope" },
  { char: "🤟", keywords: "love you sign rock" },
  { char: "🤘", keywords: "rock horns metal" },
  { char: "🤙", keywords: "call shaka hang loose" },
  { char: "👈", keywords: "point left" },
  { char: "👉", keywords: "point right" },
  { char: "👆", keywords: "point up" },
  { char: "👇", keywords: "point down" },
  { char: "☝️", keywords: "index up first" },
  { char: "✋", keywords: "raised hand high five" },
  { char: "🖐️", keywords: "five hand open" },
  { char: "🖖", keywords: "vulcan spock salute" },
  { char: "👋", keywords: "wave hi hello bye" },
  { char: "🤚", keywords: "back hand raised" },
  { char: "🖕", keywords: "middle finger fuck" },
  { char: "✍️", keywords: "writing hand pen" },
  { char: "👏", keywords: "clap applause bravo" },
  { char: "🙌", keywords: "raised hands praise hooray" },
  { char: "👐", keywords: "open hands hug" },
  { char: "🤲", keywords: "palms up dua pray" },
  { char: "🤝", keywords: "handshake deal" },
  { char: "🙏", keywords: "pray thanks please namaste" },
  { char: "💪", keywords: "muscle strong flex" },
  { char: "🦵", keywords: "leg strong" },
  { char: "🦶", keywords: "foot kick" },
  { char: "👂", keywords: "ear listen" },
  { char: "👃", keywords: "nose smell" },
  { char: "🧠", keywords: "brain smart think" },
  { char: "👀", keywords: "eyes look watching see" },
  { char: "👁️", keywords: "eye see watching" },
  { char: "👄", keywords: "mouth lips" },
  { char: "💋", keywords: "kiss lips lipstick" },
  { char: "💯", keywords: "100 hundred perfect score" },

  // Hearts & symbols
  { char: "❤️", keywords: "red heart love" },
  { char: "🧡", keywords: "orange heart" },
  { char: "💛", keywords: "yellow heart" },
  { char: "💚", keywords: "green heart" },
  { char: "💙", keywords: "blue heart" },
  { char: "💜", keywords: "purple heart" },
  { char: "🖤", keywords: "black heart" },
  { char: "🤍", keywords: "white heart" },
  { char: "🤎", keywords: "brown heart" },
  { char: "💔", keywords: "broken heart sad" },
  { char: "❣️", keywords: "heart exclamation" },
  { char: "💕", keywords: "two hearts love" },
  { char: "💞", keywords: "revolving hearts" },
  { char: "💓", keywords: "beating heart" },
  { char: "💗", keywords: "growing heart" },
  { char: "💖", keywords: "sparkling heart" },
  { char: "💘", keywords: "heart arrow cupid" },
  { char: "💝", keywords: "heart ribbon gift" },
  { char: "💟", keywords: "heart decoration" },
  { char: "🔥", keywords: "fire lit hot flame" },
  { char: "✨", keywords: "sparkles shiny stars" },
  { char: "⭐", keywords: "star yellow" },
  { char: "🌟", keywords: "glowing star sparkle" },
  { char: "💫", keywords: "dizzy star" },
  { char: "⚡", keywords: "lightning bolt zap" },
  { char: "💥", keywords: "boom collision explosion" },
  { char: "💢", keywords: "anger symbol" },
  { char: "💦", keywords: "sweat drops water" },
  { char: "💨", keywords: "dash wind speed" },
  { char: "☀️", keywords: "sun sunny" },
  { char: "🌙", keywords: "moon crescent" },
  { char: "🌈", keywords: "rainbow pride" },
  { char: "☁️", keywords: "cloud cloudy" },
  { char: "❄️", keywords: "snowflake snow cold" },
  { char: "☃️", keywords: "snowman winter" },
  { char: "💧", keywords: "droplet water tear" },
  { char: "🌊", keywords: "wave ocean water" },

  // Food
  { char: "🍕", keywords: "pizza slice food" },
  { char: "🍔", keywords: "burger hamburger food" },
  { char: "🍟", keywords: "fries food" },
  { char: "🍗", keywords: "chicken leg drumstick" },
  { char: "🍖", keywords: "meat bone" },
  { char: "🌭", keywords: "hotdog" },
  { char: "🌮", keywords: "taco mexican" },
  { char: "🌯", keywords: "burrito wrap" },
  { char: "🥪", keywords: "sandwich" },
  { char: "🍣", keywords: "sushi japanese" },
  { char: "🍜", keywords: "ramen noodles" },
  { char: "🍝", keywords: "spaghetti pasta" },
  { char: "🍲", keywords: "pot food stew" },
  { char: "🍛", keywords: "curry rice" },
  { char: "🍱", keywords: "bento box japanese" },
  { char: "🍙", keywords: "rice ball onigiri" },
  { char: "🍚", keywords: "rice bowl" },
  { char: "🍞", keywords: "bread loaf" },
  { char: "🥐", keywords: "croissant french" },
  { char: "🥖", keywords: "baguette french bread" },
  { char: "🧀", keywords: "cheese" },
  { char: "🥚", keywords: "egg" },
  { char: "🍳", keywords: "egg cooking pan" },
  { char: "🥞", keywords: "pancakes" },
  { char: "🧇", keywords: "waffle" },
  { char: "🥓", keywords: "bacon" },
  { char: "🍦", keywords: "ice cream soft serve" },
  { char: "🍰", keywords: "cake slice dessert" },
  { char: "🎂", keywords: "birthday cake" },
  { char: "🍪", keywords: "cookie" },
  { char: "🍩", keywords: "donut doughnut" },
  { char: "🍫", keywords: "chocolate bar" },
  { char: "🍬", keywords: "candy sweet" },
  { char: "🍭", keywords: "lollipop candy" },
  { char: "🍯", keywords: "honey pot" },
  { char: "🍎", keywords: "apple red" },
  { char: "🍌", keywords: "banana" },
  { char: "🍇", keywords: "grapes" },
  { char: "🍉", keywords: "watermelon" },
  { char: "🍊", keywords: "orange tangerine" },
  { char: "🍋", keywords: "lemon" },
  { char: "🍓", keywords: "strawberry" },
  { char: "🥭", keywords: "mango" },
  { char: "🍍", keywords: "pineapple" },
  { char: "🍑", keywords: "peach butt" },
  { char: "🍒", keywords: "cherries" },
  { char: "🥝", keywords: "kiwi" },
  { char: "🥑", keywords: "avocado" },
  { char: "🍅", keywords: "tomato" },
  { char: "🥕", keywords: "carrot" },
  { char: "🌽", keywords: "corn" },
  { char: "🥒", keywords: "cucumber" },
  { char: "🥬", keywords: "lettuce salad" },
  { char: "🥦", keywords: "broccoli" },
  { char: "🌶️", keywords: "chili pepper hot spicy" },
  { char: "☕", keywords: "coffee hot drink" },
  { char: "🍵", keywords: "tea cup" },
  { char: "🍺", keywords: "beer drink" },
  { char: "🍻", keywords: "beers cheers" },
  { char: "🍷", keywords: "wine glass" },
  { char: "🥂", keywords: "champagne cheers" },
  { char: "🍸", keywords: "cocktail martini" },
  { char: "🍹", keywords: "tropical drink" },
  { char: "🥤", keywords: "cup straw soda" },
  { char: "🧋", keywords: "bubble tea boba" },

  // Activities & objects
  { char: "🎉", keywords: "party tada celebration" },
  { char: "🎊", keywords: "confetti ball party" },
  { char: "🎁", keywords: "gift present" },
  { char: "🎈", keywords: "balloon party" },
  { char: "🎶", keywords: "music notes" },
  { char: "🎵", keywords: "music note" },
  { char: "🎤", keywords: "mic microphone karaoke" },
  { char: "🎧", keywords: "headphones music" },
  { char: "📱", keywords: "phone mobile cell" },
  { char: "💻", keywords: "laptop computer" },
  { char: "⌨️", keywords: "keyboard" },
  { char: "🖱️", keywords: "mouse computer" },
  { char: "🖥️", keywords: "desktop computer" },
  { char: "💾", keywords: "floppy disk save" },
  { char: "💿", keywords: "cd disc" },
  { char: "📷", keywords: "camera photo" },
  { char: "🔋", keywords: "battery" },
  { char: "🔌", keywords: "plug power" },
  { char: "🔍", keywords: "search magnifying glass" },
  { char: "🔒", keywords: "lock locked" },
  { char: "🔓", keywords: "unlock unlocked" },
  { char: "🔑", keywords: "key" },
  { char: "🔔", keywords: "bell notification" },
  { char: "📢", keywords: "loudspeaker megaphone" },
  { char: "📣", keywords: "megaphone loud" },
  { char: "📌", keywords: "pin pushpin" },
  { char: "📍", keywords: "pin location" },
  { char: "📎", keywords: "paperclip attach" },
  { char: "✂️", keywords: "scissors cut" },
  { char: "✏️", keywords: "pencil edit write" },
  { char: "📝", keywords: "memo note write" },
  { char: "📚", keywords: "books reading" },
  { char: "📖", keywords: "open book" },
  { char: "💡", keywords: "light bulb idea" },
  { char: "🔦", keywords: "flashlight torch" },
  { char: "💰", keywords: "money bag dollar" },
  { char: "💵", keywords: "dollar cash" },
  { char: "💳", keywords: "credit card" },
  { char: "💎", keywords: "gem diamond" },
  { char: "⚙️", keywords: "gear settings" },
  { char: "🔧", keywords: "wrench tool" },
  { char: "🔨", keywords: "hammer tool" },
  { char: "🛠️", keywords: "tools hammer wrench" },
  { char: "⚖️", keywords: "scales balance justice" },
  { char: "🚀", keywords: "rocket launch space" },
  { char: "✈️", keywords: "airplane plane fly" },
  { char: "🚗", keywords: "car red automobile" },
  { char: "🚕", keywords: "taxi cab" },
  { char: "🚙", keywords: "suv vehicle" },
  { char: "🚌", keywords: "bus" },
  { char: "🏠", keywords: "house home" },
  { char: "🏡", keywords: "house garden home" },
  { char: "🏢", keywords: "office building" },
  { char: "🏥", keywords: "hospital" },
  { char: "🏫", keywords: "school" },
  { char: "🌳", keywords: "tree" },
  { char: "🌲", keywords: "evergreen tree pine" },
  { char: "🌴", keywords: "palm tree tropical" },
  { char: "🌵", keywords: "cactus" },
  { char: "🌷", keywords: "tulip flower" },
  { char: "🌸", keywords: "cherry blossom flower pink" },
  { char: "🌹", keywords: "rose flower red" },
  { char: "🌺", keywords: "hibiscus flower" },
  { char: "🌻", keywords: "sunflower yellow" },
  { char: "🍀", keywords: "four leaf clover lucky" },
  { char: "🐶", keywords: "dog puppy" },
  { char: "🐱", keywords: "cat kitten" },
  { char: "🐭", keywords: "mouse" },
  { char: "🐹", keywords: "hamster" },
  { char: "🐰", keywords: "rabbit bunny" },
  { char: "🦊", keywords: "fox" },
  { char: "🐻", keywords: "bear" },
  { char: "🐼", keywords: "panda" },
  { char: "🐨", keywords: "koala" },
  { char: "🐯", keywords: "tiger" },
  { char: "🦁", keywords: "lion" },
  { char: "🐮", keywords: "cow" },
  { char: "🐷", keywords: "pig" },
  { char: "🐸", keywords: "frog" },
  { char: "🐵", keywords: "monkey" },
  { char: "🙈", keywords: "see no evil monkey" },
  { char: "🙉", keywords: "hear no evil monkey" },
  { char: "🙊", keywords: "speak no evil monkey" },

  // Symbols
  { char: "✅", keywords: "check mark green tick yes" },
  { char: "❌", keywords: "x cross no wrong" },
  { char: "⭕", keywords: "circle red big o" },
  { char: "❓", keywords: "question mark red" },
  { char: "❗", keywords: "exclamation red" },
  { char: "‼️", keywords: "double exclamation" },
  { char: "⚠️", keywords: "warning caution" },
  { char: "🚫", keywords: "prohibited no entry" },
  { char: "🆗", keywords: "ok button" },
  { char: "🆕", keywords: "new" },
  { char: "🆒", keywords: "cool" },
  { char: "🆓", keywords: "free" },
  { char: "🔝", keywords: "top up arrow" },
  { char: "🔙", keywords: "back arrow" },
  { char: "↩️", keywords: "return undo back" },
  { char: "▶️", keywords: "play forward" },
  { char: "⏸️", keywords: "pause" },
  { char: "⏹️", keywords: "stop" },
  { char: "⏯️", keywords: "play pause" },
  { char: "🔁", keywords: "repeat loop" },
  { char: "🔂", keywords: "repeat one" },
  { char: "🔀", keywords: "shuffle" },
];

/**
 * Fuzzy-filter the emoji list by query. Empty query returns all entries.
 * Match is case-insensitive substring on keywords or the character itself.
 */
export function filterEmojis(query: string): EmojiEntry[] {
  if (!query) return EMOJI_DATA;
  const q = query.toLowerCase().trim();
  return EMOJI_DATA.filter((e) => e.keywords.toLowerCase().includes(q) || e.char === q);
}
